window.teams = [
	{ title: 'Arsenal' },
	{ title: 'Aston Villa' },
	{ title: 'Chelsea' },
	{ title: 'Fulham' },
	{ title: 'Everton' },
	{ title: 'Liverpool' },
	{ title: 'Manchester City' },
	{ title: 'Manchester United' },
	{ title: 'Newcastle United' },
	{ title: 'Norwich City' },
	{ title: 'Queens Park Rangers' },
	{ title: 'Reading' },
	{ title: 'Southampton' },
	{ title: 'Stoke City' },
	{ title: 'Sunderland' },
	{ title: 'Swansea City' },
	{ title: 'Tottenham Hotspur' },
	{ title: 'West Bromwich Albion' },
	{ title: 'West Ham United' },
	{ title: 'Wigan Athletic' }
];